### ISSUE TITLE
 Ch4 - 스트림 소개 

### ISSUE THREAD

**Issue by Voyager003** [Voyager003/modern_java_in_action#9]
> 4.1 스트림이란 무엇인가?
> 4.2 스트림 시작하기
> 4.3 스트림과 컬렉션
> 4.4 스트림 연산
> 4.5 로드맵
> 4.6 마치며

해당 챕터를 정리하여 ch04 디렉토리에 있는 자신의 github id + 챕터 명으로 이뤄진 마크다운(.md) 형식으로 정리한 내용을 작성해주세요.
(e.g Voyager003_ch04)

**Comment by Wondae-code** [comment]
남는 시간에 reflection 조사를 하면 좋을 것 같아요
